---
trainers:
- _participants/sasa-juric.md
- _participants/josh-price.md
- _participants/zach-daniel.md
- _participants/lukasz-pauszek.md
- _participants/joseph-yiasemides.md
- _participants/jamie-wright.md
- _participants/michael-lubas.md
