---
trainers:
- _participants/tam-kbeili.md
- _participants/aleksander-lisiecki.md
- _participants/parker-selbert.md
- _participants/shannon-selbert.md
- _participants/josep-lluis-giralt-dlacoste.md
- _participants/laura-m-castro.md
