- from: 09.00 AM
  to: 18.00 PM
  type: training
  training_1: Debugging a running system
  training_1_url: debugging-a-running-system
  training_1_instructor: Ben Marx
  training_2: Ecto from the ground up
  training_2_instructor: Wojtek Mach
  training_2_url: ecto-from-the-ground-up
- from: 09.00 AM
  to: 18.00 PM
  type: training
  training_1: From Zero to Hero
  training_1_url: from-zero-to-hero
  training_1_instructor: Devon Estes
  training_2: Getting up to speed with Phoenix  and LiveView
  training_2_instructor: Shankar Dhanasekaran
  training_2_url: getting-up-to-speed-with-phoenix-and-liveview
- from: 09.00 AM
  to: 18.00 PM
  type: training
  training_1: Phoenix LiveView from prototype to production
  training_1_url: phoenix-liveview-from-prototype-to-production
  training_1_instructor: Mike Martinson
  training_2:
  training_2_instructor: 
  training_2_url: 
