---
trainers:
- _participants/shankar-dhanasekaran.md
- _participants/andrea-leopardi.md
- _participants/Jeffrey-matthias.md
- _participants/bartosz-blaszkow.md
- _participants/radoslaw-szuma.md
- _participants/michael-lubas.md
