---
trainers:
  - trainer: _participants/andrea-leopardi.md
  - trainer: _participants/annette-bieniusa.md
  - trainer: _participants/ben-marx.md
  - trainer: _participants/daniel-tipping.md
  - trainer: _participants/darin-wilson.md
  - trainer: _participants/devon-estes.md
  - trainer: _participants/denys-gonchar.md
  - trainer: _participants/justin-schneck.md
  - trainer: _participants/mariano-guerra.md
  - trainer: _participants/mike-martinson.md
  - trainer: _participants/shankar-dhanasekaran.md
  - trainer: _participants/tam-kbeili.md
  - trainer: _participants/wojtek-mach.md
