---
trainers:
- _participants/manuel-rubio.md
- _participants/daniel-tipping.md
- _participants/devon-estes.md
- _participants/annette-bieniusa.md
- _participants/mariano-guerra.md
- _participants/shankar-dhanasekaran.md
- _participants/andrea-leopardi.md
- _participants/denys-gonchar.md
