---
label: training-list
hide_body: true
fields:
- type: field_group_list
  name: Training
  label: Training
  fields:
  - name: item
    type: select
    default: []
    config:
      required: true
      options: []
      source:
        type: pages
        section: trainings
        file: 
        path: 
    label: item
  - name: start
    type: datetime
    label: start
    description: 'start time '
    config:
      required: true
      date_format: 
      time_format: 
      display_utc: true
  - name: end
    type: datetime
    label: end
    description: 'end time '
    config:
      required: true
      date_format: 
      time_format: 
      display_utc: true
  - name: mnemonic
    type: text
    config:
      required: true
    label: mnemonic
  config:
    labelField: mnemonic
pages:
- _data/training.yml
