---
label: Training
hide_body: false
display_field: tagline
fields:
- name: tagline
  type: text
  config:
    required: true
  label: tagline
- type: text
  name: trainer1
  label: trainer1
- type: text
  name: trainer2
  label: trainer2
- type: text
  name: experience
  label: experience
- type: text
  name: type
  label: type
