---
label: Training
hide_body: false
display_field: tagline
fields:
- name: tagline
  type: text
  config:
    required: true
  label: tagline
- type: text
  name: type
  label: type
- type: text
  name: experience
  label: experience
- name: trainer1
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: speakers
      file: 
      path: 
  label: trainer1
- name: trainer2
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: speakers
      file: 
      path: 
  label: trainer2
