---
label: training-front-page
hide_body: true
fields:
- type: field_group_list
  name: Training
  label: Training
  fields:
  - type: text
    name: from
    label: from
  - type: text
    name: to
    label: to
  - type: text
    name: type
    label: type
  - type: text
    name: training_1
    label: training_1
  - type: text
    name: training_1_url
    label: training_1_url
  - type: text
    name: training_1_instructor
    label: training_1_instructor
  - type: text
    name: training_1_instructor_2
    label: training_1_instructor_2
  - type: text
    name: training_2
    label: training_2
  - type: text
    name: training_2_url
    label: training_2_url
  - type: text
    name: training_2_instructor
    label: training_2_instructor
  - name: description
    type: text
    config:
      required: true
    label: description
    description: the description
  config:
    labelField: description

