---
label: trainer-list
hide_body: true
fields:
- name: trainers
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: speakers
  label: trainers
pages:
- _data/trainer-list.yml
