---
label: Training
hide_body: false
display_field: tagline
fields:
- name: tagline
  type: text
  config:
    required: true
  label: tagline
- type: text
  name: type
  label: type
- type: text
  name: experience
  label: experience
- name: trainers
  type: field_group_list
  fields:
  - name: trainer
    type: select
    default: []
    config:
      required: false
      options: []
      source:
        type: pages
        section: speakers
        file: 
        path: 
    label: trainer
  config:
    min: 
    max: 
    labelField: trainer
  label: trainers
pages:
- _trainings/from-zero-to-hero-with-elixir.md
- _trainings/getting-up-to-speed-with-phoenix-and-liveview.md
- _trainings/phoenix-liveview-from-prototype-to-production.md
- _trainings/rebuild-phoenix-from-scratch.md
- _trainings/tracing-elixir-in-distributed-network.md
