---
label: training-list
hide_body: true
fields:
- type: field_group_list
  name: trainings
  label: Trainings
  fields:
  - name: training
    type: select
    default: []
    config:
      required: true
      options: []
      source:
        type: pages
        section: trainings
        file: 
        path: 
    label: training
  - name: start
    type: datetime
    label: start (UTC)
    description: 'start time '
    config:
      required: true
      date_format: 
      time_format: 
      display_utc: true
  - name: end
    type: datetime
    label: end (UTC)
    description: 'end time '
    config:
      required: true
      date_format: 
      time_format: 
      display_utc: true
  config:
    labelField: ''
  description: 'use <a href="https://www.worldtimebuddy.com/" title="https://www.worldtimebuddy.com/"
    target="_blank">https://www.worldtimebuddy.com/</a> to calculate the times - enter
    them in UTC '
