---
label: Training
hide_body: false
display_field: speaker
fields:
- name: training
  type: select
  default: []
  config:
    required: true
    options: []
    source:
      type: pages
      section: trainings
      file: 
      path: 
  label: training
pages:
- _trainings/distributed-systems-with-riak-core-lite.md
- _trainings/ecto-everything-you-need-to-know.md
- _trainings/rebuild-phoenix-from-scratch.md
- _trainings/tracing-elixir-in-distributed-network.md
