---
label: Training
hide_body: false
fields:
- type: text
  name: trainer1
  label: trainer1
- type: text
  name: trainer2
  label: trainer2
- type: text
  name: experience
  label: experience
- type: text
  name: type
  label: type
