---
label: Training
hide_body: false
display_field: name
fields:
- name: name
  type: text
  config:
    required: true
  label: name
- type: text
  name: type
  label: type
- type: text
  name: experience
  label: experience
- name: trainers
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: speakers
  label: trainers
pages:
- _trainings/from-zero-to-hero-with-elixir.md
- _trainings/getting-up-to-speed-with-phoenix-and-liveview.md
- _trainings/phoenix-liveview-from-prototype-to-production.md
- _trainings/rebuild-phoenix-from-scratch.md
- _trainings/tracing-elixir-in-distributed-network.md
